CREATE DATABASE IF NOT EXISTS cadastrop1;

USE cadastrop1;

CREATE TABLE IF NOT EXISTS Cliente (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(50) NOT NULL,
  senha VARCHAR(50) NOT NULL,
  cpf VARCHAR(14) NOT NULL,
  email VARCHAR(50) NOT NULL,
  telefone VARCHAR(17) NOT NULL,
  endereco VARCHAR(50) NOT NULL,
  cidade VARCHAR(50) NOT NULL,
  estado VARCHAR(50) NOT NULL,
  cep VARCHAR(15) NOT NULL
);

